alias ba='bundle add'
alias be='bundle exec'
alias bi='bundle install'
alias bu='bundle update'

alias l='ls -lFh'
alias lS='ls -1FSsh'
alias la='ls -lAFh'
alias lart='ls -1Fcart'
alias ldot='ls -ld .*'
alias ll='ls -l'
alias lr='ls -tRFh'
alias lrt='ls -1Fcrt'
alias ls='ls --color=tty'
alias lsa='ls -lah'
alias lsn='ls -1'
alias lsr='ls -lARFh'
alias lt='ls -ltFh'

alias rr='rails routes'
alias rrc='rails routes --controller'
alias rre='rails routes --expanded'
alias rrg='rails routes --grep'
alias rru='rails routes --unused'

alias t='tail -f'
