---
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/Focus:
  AutoCorrect: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: false
