---
default: &default
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/0' } %>
  channel_prefix: divercoin_<%= Rails.env %>

development:
  <<: *default

test:
  adapter: test

production:
  <<: *default
